
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 03 19:23:44 CST 2021
//----------------------------------------------------

package tarea4;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int ID = 7;
  public static final int P_C = 6;
  public static final int NUM = 2;
  public static final int P_A = 5;
  public static final int MAS = 3;
  public static final int error = 1;
  public static final int POR = 4;
  public static final int EOF = 0;
}

